version: "3.9"

services:
  iglv-rn:
    build:
      context: .
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - "19006:19006"
      - "19000:19000"
      - "5555:5555"
    expose:
      - "19000"
      - "19006"
    volumes:
      - .:/home/node/iglv-rn
    healthcheck:
      disable: true
